#set the environment rc || prod || legacy
env: rc
#set true or false
testRailFlag: false
#set maximum number of browswer instances (1-10)
maxInstances: 1
#to stop the test on failure //Please commit with Default value: false
debug: false
watch: false
continousFailure : 20
#to see logs in console silent, error,trace
logLevel: silent
#suite id of the test run smoke:9654, regression:13256
suiteId: 13256
#upload screenshot on filure in testrail
uploadScreenShotInTestRail: true
#produc: he_sapling,ca_sapling
product: he_sapling
